"""empty message

Revision ID: 53c8a4f67507
Revises: 
Create Date: 2021-02-11 21:42:08.286511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8a4f67507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_on')
    op.drop_column('tasks', 'created_on')
    # ### end Alembic commands ###
