"""empty message

Revision ID: 7105b8580e5a
Revises: 3fef2e4532b4
Create Date: 2021-03-25 14:02:33.540460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7105b8580e5a'
down_revision = '3fef2e4532b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('book', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('book', 'description')
    op.drop_column('book', 'book_id')
    # ### end Alembic commands ###
