"""empty message

Revision ID: c1c34b476a66
Revises: 7105b8580e5a
Create Date: 2021-03-25 20:59:51.727554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c34b476a66'
down_revision = '7105b8580e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('book', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('book', 'id')
    # ### end Alembic commands ###
